/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#006672",
        secondary: "#3b6934",
        "on-secondary-fixed-variant": "#23501e",
        "on-primary-fixed": "#001f24",
        "surface-tint": "#006875",
        "on-tertiary-container": "#4f3e00",
        "surface-container": "#edeeef",
        "primary-fixed": "#9eefff",
        "on-secondary-fixed": "#002201",
        "on-primary-container": "#f8feff",
        "inverse-surface": "#2e3132",
        "tertiary-fixed": "#ffe088",
        "secondary-container": "#b9eeab",
        "on-background": "#191c1d",
        background: "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#3f6d38",
        "tertiary-fixed-dim": "#e9c349",
        tertiary: "#735c00",
        "on-tertiary-fixed-variant": "#574500",
        "surface-container-high": "#e7e8e9",
        surface: "#f8f9fa",
        "primary-fixed-dim": "#6fd5e7",
        "inverse-on-surface": "#f0f1f2",
        "on-surface-variant": "#3e494b",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-container": "#cca730",
        "inverse-primary": "#6fd5e7",
        "on-surface": "#191c1d",
        "secondary-fixed-dim": "#a1d494",
        "surface-bright": "#f8f9fa",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#004e59",
        "surface-container-highest": "#e1e3e4",
        "outline-variant": "#bdc9cb",
        "surface-dim": "#d9dadb",
        "primary-container": "#008190",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#241a00",
        "surface-container-lowest": "#ffffff",
        outline: "#6e797c",
        "secondary-fixed": "#bcf0ae",
        "surface-variant": "#e1e3e4"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        md: "24px",
        "margin-mobile": "16px",
        gutter: "24px",
        xs: "4px",
        base: "8px",
        "margin-desktop": "64px",
        sm: "12px",
        lg: "48px",
        xl: "80px"
      },
      fontFamily: {
        "headline-md": ["Montserrat"],
        "label-md": ["Inter"],
        "display-lg-mobile": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "body-md": ["Inter"],
        "headline-sm": ["Montserrat"],
        "body-lg": ["Inter"],
        "caption": ["Inter"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
